-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 09:33:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema web_chris
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_chris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_chris` DEFAULT CHARACTER SET utf8mb4 ;
USE `web_chris` ;

-- -----------------------------------------------------
-- Table `web_chris`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`tb_usuario` (
  `idUsuario` INT(20) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Nick` VARCHAR(100) NOT NULL,
  `Contra` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `rutaImg` VARCHAR(300) NOT NULL,
  `BalanceCuenta` FLOAT NULL DEFAULT NULL,
  `FechaAlta` DATETIME NOT NULL,
  `Estatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `Nick` (`Nick` ASC));


-- -----------------------------------------------------
-- Table `web_chris`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`cuenta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `FechaCuenta` DATETIME NOT NULL,
  `idUsuarioFK` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuarioFK` (`idUsuarioFK` ASC),
  CONSTRAINT `cuenta_ibfk_1`
    FOREIGN KEY (`idUsuarioFK`)
    REFERENCES `web_chris`.`tb_usuario` (`idUsuario`));


-- -----------------------------------------------------
-- Table `web_chris`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `web_chris`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `web_chris`.`tb_acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`tb_acciones` (
  `idAcciones` INT(10) NOT NULL AUTO_INCREMENT,
  `ticket` VARCHAR(200) NOT NULL,
  `stop` VARCHAR(200) NOT NULL,
  `entrada` VARCHAR(200) NOT NULL,
  `salida` VARCHAR(200) NOT NULL,
  `acciones` VARCHAR(200) NOT NULL,
  `utilidad` VARCHAR(200) NOT NULL,
  `setup` VARCHAR(200) NOT NULL,
  `inversion` VARCHAR(200) NOT NULL,
  `Open` TINYINT(4) NOT NULL,
  `idUsuario` VARCHAR(200) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Estatus` TINYINT(3) NOT NULL,
  PRIMARY KEY (`idAcciones`));


-- -----------------------------------------------------
-- Table `web_chris`.`tb_formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`tb_formulario` (
  `idFormulario` INT(20) NOT NULL AUTO_INCREMENT,
  `Dia` VARCHAR(50) NULL DEFAULT NULL,
  `Ticket` VARCHAR(10) NULL DEFAULT NULL,
  `Strike` FLOAT NULL DEFAULT NULL,
  `Contrato` INT(11) NULL DEFAULT NULL,
  `DiasVencimiento` INT(11) NULL DEFAULT NULL,
  `FechaEntrega` VARCHAR(200) NULL DEFAULT NULL,
  `Operacion1` VARCHAR(20) NULL DEFAULT NULL,
  `Operacion2` VARCHAR(20) NULL DEFAULT NULL,
  `Operacion3` VARCHAR(20) NULL DEFAULT NULL,
  `FechaSalida` VARCHAR(200) NULL DEFAULT NULL,
  `Volumen` FLOAT NULL DEFAULT NULL,
  `PrecioInt` FLOAT NULL DEFAULT NULL,
  `PrecioChris` FLOAT NULL DEFAULT NULL,
  `VentaOpcion` FLOAT NULL DEFAULT NULL,
  `Costo` FLOAT NULL DEFAULT NULL,
  `Rentabilidad` FLOAT NULL DEFAULT NULL,
  `Nick` VARCHAR(200) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Estatus` TINYINT(2) NOT NULL,
  PRIMARY KEY (`idFormulario`),
  INDEX `idUsuario` (`Nick` ASC),
  CONSTRAINT `fk_usuario_formulario`
    FOREIGN KEY (`Nick`)
    REFERENCES `web_chris`.`tb_usuario` (`Nick`));


-- -----------------------------------------------------
-- Table `web_chris`.`tb_futuros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`tb_futuros` (
  `idFuturo` INT(10) NOT NULL AUTO_INCREMENT,
  `ticket` VARCHAR(200) NOT NULL,
  `stop` VARCHAR(200) NOT NULL,
  `entrada` VARCHAR(200) NOT NULL,
  `salida` VARCHAR(200) NOT NULL,
  `contrato` VARCHAR(200) NOT NULL,
  `puntos` VARCHAR(200) NOT NULL,
  `utilidad` VARCHAR(200) NOT NULL,
  `setup` VARCHAR(200) NOT NULL,
  `Open` TINYINT(3) NOT NULL,
  `idUsuario` VARCHAR(200) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Estatus` TINYINT(3) NOT NULL,
  PRIMARY KEY (`idFuturo`));


-- -----------------------------------------------------
-- Table `web_chris`.`tb_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`tb_log` (
  `idLog` INT(10) NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(100) NOT NULL,
  `Accion` VARCHAR(100) NOT NULL,
  `Pantalla` VARCHAR(100) NOT NULL,
  `Rol` VARCHAR(100) NOT NULL,
  `Lectura_Noti` INT(10) NOT NULL,
  `FechaAccion` DATETIME NOT NULL,
  `Status` TINYINT(2) NOT NULL,
  PRIMARY KEY (`idLog`));


-- -----------------------------------------------------
-- Table `web_chris`.`tb_opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`tb_opciones` (
  `idOpcion` INT(11) NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(100) NOT NULL,
  `hora` VARCHAR(100) NOT NULL,
  `ticket` VARCHAR(100) NOT NULL,
  `strike` VARCHAR(200) NULL DEFAULT NULL,
  `contrato` VARCHAR(200) NULL DEFAULT NULL,
  `diasvencimiento` VARCHAR(200) NULL DEFAULT NULL,
  `fechaentrada` VARCHAR(100) NOT NULL,
  `put_call` VARCHAR(100) NOT NULL,
  `compra_venta` VARCHAR(100) NOT NULL,
  `shor_long` VARCHAR(100) NOT NULL,
  `fechsasalida` VARCHAR(100) NOT NULL,
  `preciochris` VARCHAR(200) NULL DEFAULT NULL,
  `ventachris` VARCHAR(200) NULL DEFAULT NULL,
  `dinero` VARCHAR(200) NULL DEFAULT NULL,
  `rentabilidad` VARCHAR(200) NULL DEFAULT NULL,
  `Nick` VARCHAR(100) NOT NULL,
  `tiempo_total` VARCHAR(200) NULL DEFAULT NULL,
  `Open` VARCHAR(200) NULL DEFAULT NULL,
  `idUsuario` FLOAT NULL DEFAULT NULL,
  `Fecha` VARCHAR(100) NOT NULL,
  `Estatus` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idOpcion`));


-- -----------------------------------------------------
-- Table `web_chris`.`tb_opciones_copy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`tb_opciones_copy` (
  `idOpcion` INT(11) NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(100) NOT NULL,
  `hora` VARCHAR(100) NOT NULL,
  `ticket` VARCHAR(100) NOT NULL,
  `strike` VARCHAR(200) NULL DEFAULT NULL,
  `contrato` VARCHAR(200) NULL DEFAULT NULL,
  `diasvencimiento` VARCHAR(200) NULL DEFAULT NULL,
  `fechaentrada` VARCHAR(100) NOT NULL,
  `put_call` VARCHAR(100) NOT NULL,
  `compra_venta` VARCHAR(100) NOT NULL,
  `shor_long` VARCHAR(100) NOT NULL,
  `fechsasalida` VARCHAR(100) NOT NULL,
  `preciochris` VARCHAR(200) NULL DEFAULT NULL,
  `ventachris` VARCHAR(200) NULL DEFAULT NULL,
  `dinero` VARCHAR(200) NULL DEFAULT NULL,
  `rentabilidad` VARCHAR(200) NULL DEFAULT NULL,
  `Nick` VARCHAR(100) NOT NULL,
  `tiempo_total` VARCHAR(200) NULL DEFAULT NULL,
  `Open` VARCHAR(200) NULL DEFAULT NULL,
  `Fecha` VARCHAR(100) NOT NULL,
  `Estatus` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`idOpcion`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `web_chris`.`weekdays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_chris`.`weekdays` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
